kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-networkdisk-smbshare
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.usedBySambaServer.storageSize }}
  storageClassName: {{ .Values.persistentVolumeClaim.usedBySambaServer.referStorageClass }}




  