{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: smbcreds
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  username: {{ .Values.secrets.username | default (randAlphaNum 8) | b64enc | quote }}
  password: {{ .Values.secrets.password | default (randAlphaNum 16) | b64enc | quote }}
{{- end }}