apiVersion: v1
kind: Service
metadata:
  name: {{ include "samba-server.fullname" . }}
  labels:
    {{- include "samba-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: samba-port
      protocol: TCP
      name: samba-port
  selector:
    {{- include "samba-server.selectorLabels" . | nindent 4 }}
