name: ci

on:
  push:
    branches:
      - "master"
    tags:
      - '*.*.*'

jobs:
  build-publish-containers:
    name: Build and Publish Containers
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 2
      matrix:
        os: [ubuntu-latest, ubuntu-latest]
        include:
        - os: ubuntu-latest
          style: "-not-recycle"
          file: Dockerfile
        - os: ubuntu-latest
          file: Dockerfile.not_recycle
          style: ""

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./${{ matrix.file }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/samba:latest${{ matrix.style }}, ${{ secrets.DOCKER_HUB_USERNAME }}/samba:${{ env.RELEASE_VERSION }}${{ matrix.style }}
